# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: Upload index.html to S3
on:
  push
env:
  BUCKET_NAME : "coba00.letak.in"
  AWS_REGION : "ap-southeast-1"
# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2
jobs:
  S3PackageUpload:
    runs-on: self-hosted
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::933547176900:role/StaticSiteDeployRoleStack-s3deployrole3DA131ED-1FD69PW6EBP11
          role-session-name: uploadtos3session
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E318NHP7GWDI21 --paths '/*'
